# Generated by Django 6.0.8 on 2026-09-27 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_adopt_existing_recipes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_favorite',
        ),
    ]
